import type { ChartConfig, LineSeriesConfig, AreaSeriesConfig, BarSeriesConfig, ScatterSeriesConfig } from '@/types/chart-config'

export const PALETTE = ['#8884d8', '#82ca9d', '#ffc658', '#ff7300', '#00C49F', '#d45087', '#665191', '#2f4b7c', '#a05195', '#f95d6a']

export function makeLineSeries(dataKey: string, name: string, color: string): LineSeriesConfig {
  return {
    dataKey, name, color,
    type: 'monotone',
    strokeWidth: 2,
    strokeDasharray: '',
    showDots: true,
    dotSize: 4,
    dotFill: color,
    dotStroke: '#fff',
    dotStrokeWidth: 2,
    showActiveDot: true,
    activeDotSize: 6,
    connectNulls: false,
    hide: false,
    showLabel: false,
    labelPosition: 'top',
    labelFontSize: 11,
    legendType: 'line',
    unit: '',
    animationBegin: 0,
    animationDuration: 1500,
    animationEasing: 'ease',
  }
}

export function makeAreaSeries(dataKey: string, name: string, color: string): AreaSeriesConfig {
  return {
    ...makeLineSeries(dataKey, name, color),
    showDots: false,
    fillColor: color,
    fillOpacity: 0.3,
    stackId: '',
    legendType: 'rect',
  }
}

export function makeBarSeries(dataKey: string, name: string, color: string): BarSeriesConfig {
  return {
    dataKey, name, color,
    strokeColor: 'none',
    strokeWidth: 0,
    barSize: undefined,
    maxBarSize: 150,
    minPointSize: 0,
    radius: [0, 0, 0, 0],
    stackId: '',
    showBackground: false,
    backgroundFill: '#f5f5f5',
    backgroundRadius: 0,
    showLabel: false,
    labelPosition: 'top',
    labelFontSize: 11,
    labelColor: '#666',
    hide: false,
    legendType: 'rect',
    unit: '',
    animationBegin: 0,
    animationDuration: 400,
    animationEasing: 'ease',
  }
}

export function makeScatterSeries(name: string, color: string): ScatterSeriesConfig {
  return {
    name, color,
    shape: 'circle',
    showLine: false,
    lineType: 'joint',
    lineJointType: 'linear',
    showLabel: false,
    labelPosition: 'top',
    labelFontSize: 11,
    hide: false,
    legendType: 'circle',
    animationBegin: 0,
    animationDuration: 400,
    animationEasing: 'linear',
  }
}

export const DEFAULT_CONFIG: ChartConfig = {
  chartType: 'line',
  chartWidth: 920,
  chartHeight: 400,
  containerPadding: 24,
  backgroundColor: '#1c1c1c',
  margin: { top: 24, right: 24, bottom: 0, left: 24 },
  animationEnabled: false,
  title: {
    show: false,
    text: '',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: 24,
    fontColor: '#e5e5e5',
    align: 'left',
    subtitle: '',
    subtitleFontSize: 13,
    subtitleFontWeight: 400,
    subtitleLineHeight: 18,
    subtitleFontColor: '#999',
  },

  chartLayout: {
    layout: 'horizontal',
    stackOffset: 'none',
    reverseStackOrder: false,
    barCategoryGap: 10,
    barGap: 4,
    barSize: undefined,
    maxBarSize: 150,
  },

  lineSeries: [
    makeLineSeries('series1', 'Series 1', PALETTE[0]),
    makeLineSeries('series2', 'Series 2', PALETTE[1]),
    makeLineSeries('series3', 'Series 3', PALETTE[2]),
  ],
  areaSeries: [
    makeAreaSeries('series1', 'Series 1', PALETTE[0]),
    makeAreaSeries('series2', 'Series 2', PALETTE[1]),
    makeAreaSeries('series3', 'Series 3', PALETTE[2]),
  ],
  barSeries: [
    makeBarSeries('series1', 'Series 1', PALETTE[0]),
    makeBarSeries('series2', 'Series 2', PALETTE[1]),
    makeBarSeries('series3', 'Series 3', PALETTE[2]),
  ],
  pie: {
    dataKey: 'value',
    nameKey: 'name',
    cx: '50%',
    cy: '50%',
    innerRadius: 0,
    outerRadius: 80,
    cornerRadius: 0,
    startAngle: 0,
    endAngle: 360,
    paddingAngle: 0,
    minAngle: 0,
    stroke: '#fff',
    strokeWidth: 1,
    showLabels: true,
    labelFontSize: 12,
    showLabelLine: true,
    slices: [
      { name: 'Electronics', color: PALETTE[0] },
      { name: 'Clothing', color: PALETTE[1] },
      { name: 'Food', color: PALETTE[2] },
      { name: 'Books', color: PALETTE[3] },
      { name: 'Other', color: PALETTE[4] },
    ],
    animationBegin: 400,
    animationDuration: 1500,
    animationEasing: 'ease',
  },
  scatterSeries: [makeScatterSeries('Series 1', PALETTE[0])],

  xAxis: {
    show: true,
    dataKey: 'name',
    type: 'category',
    orientation: 'bottom',
    label: '',
    labelFontSize: 12,
    labelPosition: 'insideBottom',
    tickCount: 5,
    tickSize: 6,
    tickLine: true,
    tickMargin: 5,
    tickRotation: 0,
    tickFontSize: 12,
    tickFill: '#999',
    minTickGap: 5,
    interval: 'preserveEnd',
    axisLine: true,
    axisLineStroke: '#666',
    paddingStart: 0,
    paddingEnd: 0,
    mirror: false,
    reversed: false,
    allowDecimals: true,
    allowDataOverflow: false,
    scale: 'auto',
    size: 30,
  },
  yAxis: {
    show: true,
    dataKey: '',
    type: 'number',
    orientation: 'left',
    label: '',
    labelFontSize: 12,
    labelPosition: 'insideLeft',
    tickCount: 5,
    tickSize: 6,
    tickLine: true,
    tickMargin: 5,
    tickRotation: 0,
    tickFontSize: 12,
    tickFill: '#999',
    minTickGap: 5,
    interval: 'preserveEnd',
    axisLine: true,
    axisLineStroke: '#666',
    paddingStart: 0,
    paddingEnd: 0,
    mirror: false,
    reversed: false,
    allowDecimals: true,
    allowDataOverflow: false,
    scale: 'auto',
    size: 'auto',
  },

  legend: {
    show: true,
    layout: 'horizontal',
    align: 'center',
    verticalAlign: 'bottom',
    iconSize: 14,
    iconType: 'rect',
    fontSize: 12,
    fontColor: '#999',
    inactiveColor: '#ccc',
    marginTop: 0,
    marginBottom: 0,
  },

  grid: {
    show: true,
    horizontal: true,
    vertical: true,
    stroke: '#444',
    strokeDasharray: '3 3',
    fill: 'none',
    fillOpacity: 0,
    syncWithTicks: false,
  },

  tooltip: {
    show: true,
    trigger: 'hover',
    shared: true,
    separator: ' : ',
    offset: 10,
    filterNull: true,
    cursor: true,
    cursorStroke: '#999',
    cursorStrokeDasharray: '3 3',
    useTranslate3d: false,
    backgroundColor: '#2c2c2c',
    borderColor: '#555',
    borderRadius: 4,
    fontSize: 12,
    fontColor: '#e5e5e5',
    labelFontSize: 12,
    labelColor: '#e5e5e5',
    animationDuration: 400,
    animationEasing: 'ease',
    allowEscapeViewBoxX: false,
    allowEscapeViewBoxY: false,
  },

  brush: {
    show: false,
    height: 40,
    stroke: '#666',
    fill: '#383838',
    travellerWidth: 5,
    gap: 1,
    dataKey: 'name',
  },

  referenceLines: [],
  referenceAreas: [],
}
